# -*- coding: utf-8 -*-
"""lab6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keucr_pYovXXlwhV4BbnFp5CKVituSO-
"""

!pip install scikit-fuzzy numpy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# 1. Define the Variables (Input and Output)
# Occupancy range: 0 to 10 people
occupancy = ctrl.Antecedent(np.arange(0, 11, 1), 'occupancy')

# Cooling Power range: 0% to 100%
cooling_power = ctrl.Consequent(np.arange(0, 101, 1), 'cooling_power')

# 2. Define Membership Functions (Triangular)
# low: Peak at 0, drops to 0 at 5 (triangular parameter layout: [start, peak, end])
occupancy['low'] = fuzz.trimf(occupancy.universe, [0, 0, 5])

# high: Starts at 4, peaks at 10, ends at 10 (stays at peak)
occupancy['high'] = fuzz.trimf(occupancy.universe, [4, 10, 10])

# Define output states for cooling power
cooling_power['low_power'] = fuzz.trimf(cooling_power.universe, [0, 0, 60])
cooling_power['high_power'] = fuzz.trimf(cooling_power.universe, [40, 100, 100])

# 3. Define the Knowledge Base (Fuzzy Rules)
rule1 = ctrl.Rule(occupancy['low'], cooling_power['low_power'])
rule2 = ctrl.Rule(occupancy['high'], cooling_power['high_power'])

# 4. Create and Simulate the Control System
ac_control = ctrl.ControlSystem([rule1, rule2])
ac_simulator = ctrl.ControlSystemSimulation(ac_control)

# Pass the crisp test value (7 people) to the system
test_occupancy = 7
ac_simulator.input['occupancy'] = test_occupancy

# Perform the fuzzy inference processing
ac_simulator.compute()

# Output the defuzzified crisp result
print(f"--- Smart Air Conditioning System Output ---")
print(f"Room Occupancy Input: {test_occupancy} people")
print(f"Calculated Target Cooling Power: {ac_simulator.output['cooling_power']:.2f}%")

# ==========================================
# STEP 3: Define the Knowledge Base (Rules)
# ==========================================

# Rule 1: IF occupancy is low, THEN cooling power is low_power
rule1 = ctrl.Rule(occupancy['low'], cooling_power['low_power'])

# Rule 2: IF occupancy is high, THEN cooling power is high_power
rule2 = ctrl.Rule(occupancy['high'], cooling_power['high_power'])

# ==================================================
# STEP 4: Create and Simulate the Control System
# ==================================================

# 1. Combine the rules into a control system
ac_control = ctrl.ControlSystem([rule1, rule2])
ac_simulator = ctrl.ControlSystemSimulation(ac_control)

# 2. Pass the crisp test value (7 people) to the system
ac_simulator.input['occupancy'] = 7

# 3. Perform the fuzzy inference processing
ac_simulator.compute()

# 4. Output the defuzzified crisp result
print(f"--- Smart Air Conditioning System Output ---")
print(f"Calculated Target Cooling Power: {ac_simulator.output['cooling_power']:.2f}%")